#!/usr/bin/env node
// Writes apps/mobile/.env.local so a PHYSICAL PHONE on the same Wi-Fi can reach the local Supabase
// running on this Mac. LOCAL DEVELOPMENT ONLY.
//
//   pnpm mobile:env                 # auto-detect this Mac's LAN IP
//   pnpm mobile:env -- --host 192.168.1.82
//
// Only the public anon key is written. The service-role key is never read into the output.

import { execFileSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';
import { networkInterfaces } from 'node:os';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const repoRoot = join(dirname(fileURLToPath(import.meta.url)), '..', '..');
const target = join(repoRoot, 'apps', 'mobile', '.env.local');

function fail(message) {
  console.error(`\n✖ ${message}\n`);
  process.exit(1);
}

function lanAddress() {
  const override = process.argv.indexOf('--host');
  if (override !== -1) {
    const host = process.argv[override + 1];
    if (!host) fail('--host needs a value, e.g. --host 192.168.1.82');
    return host;
  }
  const candidates = [];
  for (const [name, addrs] of Object.entries(networkInterfaces())) {
    for (const a of addrs ?? []) {
      if (a.family === 'IPv4' && !a.internal && !a.address.startsWith('169.254.')) candidates.push({ name, address: a.address });
    }
  }
  // Prefer the Wi-Fi/Ethernet interface (en*) over VPN/bridge interfaces.
  candidates.sort((a, b) => Number(!a.name.startsWith('en')) - Number(!b.name.startsWith('en')));
  if (candidates.length === 0) fail('No LAN IPv4 address found. Is this Mac connected to Wi-Fi?');
  return candidates[0].address;
}

let statusEnv;
try {
  statusEnv = execFileSync('pnpm', ['exec', 'supabase', 'status', '-o', 'env'], {
    cwd: repoRoot,
    encoding: 'utf8',
    stdio: ['ignore', 'pipe', 'ignore'],
  });
} catch {
  fail('Local Supabase is not running. Start it with: pnpm db:start');
}

const read = (key) => statusEnv.match(new RegExp(`^${key}="?([^"\\n]+)"?$`, 'm'))?.[1];
const apiUrl = read('API_URL');
const anonKey = read('ANON_KEY');
if (!apiUrl || !anonKey) fail('Could not read API_URL / ANON_KEY from `supabase status`.');

// Defence in depth: refuse anything that is not the anon role.
const payload = JSON.parse(Buffer.from(anonKey.split('.')[1] ?? '', 'base64url').toString('utf8') || '{}');
if (payload.role !== 'anon') fail(`Refusing to write a key with role "${payload.role}". Only the anon key may go in the app.`);

const port = new URL(apiUrl).port || '55321';
const host = lanAddress();
const url = `http://${host}:${port}`;

writeFileSync(
  target,
  [
    '# Generated by `pnpm mobile:env` for LOCAL DEVELOPMENT. Git-ignored. Re-run if your Mac\'s IP changes.',
    '# Public values only. NEVER put the service-role key in this file.',
    `EXPO_PUBLIC_SUPABASE_URL=${url}`,
    `EXPO_PUBLIC_SUPABASE_ANON_KEY=${anonKey}`,
    '',
  ].join('\n'),
);

console.log(`✔ Wrote apps/mobile/.env.local\n  EXPO_PUBLIC_SUPABASE_URL=${url}\n  EXPO_PUBLIC_SUPABASE_ANON_KEY=${anonKey.slice(0, 12)}… (anon)`);
console.log('  Restart `pnpm mobile` so Expo picks up the new values.');
